export { ReactComponent as GithubIcon } from './assets/github-icon.svg';
export { ReactComponent as PinIcon } from './assets/pin-icon.svg';
export { ReactComponent as TermometerIcon } from './assets/termometer-icon.svg';
export { ReactComponent as HumidityIcon } from './assets/humidity-icon.svg';
export { ReactComponent as PrecipitationIcon } from './assets/precipitation-icon.svg';
export { ReactComponent as DropsIcon } from './assets/drops-icon.svg';
export { ReactComponent as SnowflakeIcon } from './assets/snowflake-icon.svg';
export { ReactComponent as SearchIcon } from './assets/search-icon.svg';
export { ReactComponent as GpsIcon } from './assets/gps-icon.svg';
